version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
     - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8030:80
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
